# Generated by Django 5.0.7 on 2024-08-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookorder',
            table='front_book_order',
        ),
    ]
