[DATABASE]
# 数据库类型，仅支持 'sqlite' 或 'mysql'
DB_TYPE = mysql
DB_CONFIG = {'sqlite': {'database': 'sqlite_ptvicomo.db'},'mysql': {'host': '192.168.112.13','port': 3306,'user':  'root','password': 'Lghgs2019','database': 'easyspide','charset': 'utf8mb4'}}
TABLE_NAME = pt_vicomo_01
[DEFAULT]
WEB_COOKIE = [{'domain': 'ptvicomo.net', 'expiry': 1749948891, 'httpOnly': True, 'name': 'c_secure_login', 'path': '/','sameSite': 'Lax', 'secure': False, 'value': 'bm9wZQ%3D%3D'},{'domain': 'ptvicomo.net', 'expiry': 1749948891, 'httpOnly': True, 'name': 'c_secure_tracker_ssl','path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'eWVhaA%3D%3D'},{'domain': 'ptvicomo.net', 'expiry': 1749948891, 'httpOnly': True, 'name': 'c_secure_ssl', 'path': '/','sameSite': 'Lax', 'secure': False, 'value': 'eWVhaA%3D%3D'},{'domain': 'ptvicomo.net', 'expiry': 1749948891, 'httpOnly': True, 'name': 'c_secure_pass', 'path': '/','sameSite': 'Lax', 'secure': False, 'value': '14c96bacdf049a639abbe1b38199655d'},{'domain': 'ptvicomo.net', 'expiry': 1749948891, 'httpOnly': True, 'name': 'c_secure_uid', 'path': '/','sameSite': 'Lax', 'secure': False, 'value': 'MjI1MzM%3D'}]
WEBSITE_MAIN_URL = https://ptvicomo.net/index.php
WEBSITE_URL = https://ptvicomo.net/customgame.php
LOGIN_USERNAME = ledor2024
LOGIN_PASSWORD = VvyNFQ*!Q]Bv5^'
WAIT_TIMEOUT = 5
# 保存页面
SAVE_PAGE = False
# 无头模式
HEAD_LESS = True
[TRADE]
# 动作类型
CURRENT_ACTION = {'buy': '买入', 'sale': '卖出', 'get_data': '提取数据'}
# 买入数量（必须为非负整数）
BUY_NUMBER = 1
# 卖出数量（必须为非负整数）
SALE_NUMBER = 0
# 利润率（必须为正数，达到该值则自动卖出）
PROFIT_MARGIN = 10

