# Generated by Django 5.0.7 on 2024-08-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pub_time', models.DateField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
