# Generated by Django 5.0.7 on 2024-08-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pub_time']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
