# Generated by Django 5.0.7 on 2024-08-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_user_alter_book_options_alter_book_table_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
