# Generated by Django 5.0.7 on 2024-08-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_date_added_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='auth',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.auth', verbose_name='外键作者'),
        ),
    ]
