"""
登录
"""
import sys
from tkinter.tix import Form

# Form implementation generated from reading ui file '登录.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget, QMessageBox

from dao import userDao
from entity.UserModel import User


class Ui_Form(QWidget):  # 原来是继承自object，现在改成了QWidget。但是为什么？
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 70, 261, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(25)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.username_input = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.username_input.setObjectName("username_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.username_input)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.password_input = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password_input)
        self.login_Btn = QtWidgets.QPushButton(parent=Form)
        self.login_Btn.setGeometry(QtCore.QRect(80, 250, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/mine.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.login_Btn.setIcon(icon)
        self.login_Btn.setObjectName("login_Btn")

        # 绑定登录按钮
        self.login_Btn.clicked.connect(self.login)

        self.reset_Btn = QtWidgets.QPushButton(parent=Form)
        self.reset_Btn.setGeometry(QtCore.QRect(220, 250, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reset_Btn.setIcon(icon1)
        self.reset_Btn.setObjectName("reset_Btn")

        # 重置按钮绑定点击事件的槽函数
        self.reset_Btn.clicked.connect(self.resetForm)

        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(37, 11, 61, 50))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("./images/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "密    码："))
        self.login_Btn.setText(_translate("Form", "登录"))
        self.reset_Btn.setText(_translate("Form", "重置"))
        self.label_3.setText(_translate("Form", "图书管理系统"))

    def resetForm(self):
        """
        重置表单
        :return:
        """
        self.username_input.setText("")
        self.password_input.setText("")

    def login(self):
        userName = self.username_input.text()
        password = self.password_input.text()
        if userName.strip() == "" or password.strip() == "":
            QMessageBox.warning(None, "系统提示", "用户名或密码不能为空!")
        else:
            user = User(userName, password)
            resultUser = userDao.login(user)
            if resultUser:
                QMessageBox.information(None, "系统提示", "用户登录成功!")
            else:
                QMessageBox.warning(None, "系统提示", "用户名或密码错误")


def main():
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Form()
    ui.show()
    sys.exit(app.exec())


if __name__ == '__main__':
    main()
