# Generated by Django 5.0.7 on 2024-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcomment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
