# Generated by Django 5.0.7 on 2024-08-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcomment_pub_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-pub_time'], 'verbose_name': '博客评论', 'verbose_name_plural': '博客评论'},
        ),
    ]
