# Generated by Django 4.1.3 on 2022-11-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="qq",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
