# Generated by Django 5.0.7 on 2024-08-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=200)),
                ('dept_phone', models.CharField(max_length=200)),
                ('dept_tel', models.CharField(max_length=200)),
                ('dept_state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=20)),
                ('org_name', models.CharField(max_length=200)),
                ('org_desc', models.CharField(max_length=200)),
                ('org_img', models.CharField(max_length=200)),
                ('org_address', models.CharField(max_length=200)),
                ('org_city', models.CharField(max_length=200)),
                ('org_tel', models.CharField(max_length=200)),
                ('is_primary', models.BooleanField()),
                ('org_state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=20)),
                ('position_name', models.CharField(max_length=200)),
                ('position_desc', models.CharField(max_length=200)),
                ('position_state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20)),
                ('login_password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('job_date', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('resume', models.CharField(max_length=500)),
                ('responsibility', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=200)),
                ('position_id', models.CharField(max_length=200)),
                ('org_id', models.CharField(max_length=20)),
                ('dept_id', models.CharField(max_length=20)),
                ('state', models.BooleanField()),
            ],
        ),
    ]
