# Generated by Django 5.0.7 on 2024-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_user', '0003_alter_user_managers_rename_state_user_user_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_name',
            new_name='chinese_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id_card',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='111111', max_length=20),
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_state',
        ),
    ]
