# Generated by Django 5.0.7 on 2024-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_user', '0004_rename_login_name_user_chinese_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'id_card', 'telephone')},
        ),
    ]
