# Generated by Django 5.0.7 on 2024-08-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_user', '0005_alter_user_unique_together_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captchamodel',
            old_name='phone',
            new_name='telephone',
        ),
    ]
