# Generated by Django 5.0.7 on 2024-08-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hg_user', '0006_rename_phone_captchamodel_telephone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='HgUser',
        ),
    ]
