# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSearchHelloWorld():
    def setup_method(self, method):
        service = ChromeService(executable_path='D:\\google_chrome\\chromedriver-win64\\chromedriver.exe')
        self.driver = webdriver.Chrome(service=service)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_searchHelloWorld(self):
        # Test name: SearchHelloWorld
        # Step # | name | target | value
        # 1 | times | 10 |
        for i in range(0, 1):
            # 2 | open | / |
            self.driver.get("https://www.baidu.com/")

            # 3 | click | id=kw |
            self.driver.find_element(By.ID, "kw").click()
            # 4 | type | id=kw | hello world
            self.driver.find_element(By.ID, "kw").send_keys("hello world")
            # 5 | click | id=su |
            self.driver.find_element(By.ID, "su").click()
            # 6 | waitForElementVisible | xpath=//span[contains(text(),' - 百度百科')] | 30000
            WebDriverWait(self.driver, 30).until(
                expected_conditions.visibility_of_element_located(
                    (By.XPATH, "//span[contains(text(),\' - 百度百科\')]")))
            # 7 | assertElementPresent | xpath=//span[contains(text(),' - 百度百科')] |
            elements = self.driver.find_elements(By.XPATH, "//span[contains(text(),\' - 百度百科\')]")
            assert len(elements) > 0
            # 8 | end |  |
